import { Router } from 'express';
import * as chatController from '../controllers/chatController.js';
import { authenticate, requirePermission } from '../middlewares/authenticate.js';
import { resolveHotel, enforceTenantAccess } from '../middlewares/tenantScope.js';
import { PERMISSIONS } from '../constants/permissions.js';
const router = Router({ mergeParams: true });
router.use(authenticate);
router.post('/conversations', resolveHotel, chatController.startConversation);
router.get('/conversations/my', chatController.getMyConversations);
router.get('/conversations/:conversationId', chatController.getConversationById);
router.get('/conversations/:conversationId/messages', chatController.getMessages);
router.post('/conversations/:conversationId/messages', chatController.sendMessage);
router.post('/conversations/:conversationId/read', chatController.markAsRead);
router.get('/conversations', resolveHotel, enforceTenantAccess, requirePermission(PERMISSIONS.CHAT_VIEW), chatController.getHotelConversations);
router.patch('/conversations/:conversationId/assign', resolveHotel, enforceTenantAccess, requirePermission(PERMISSIONS.CHAT_RESPOND), chatController.assignConversation);
router.patch('/conversations/:conversationId/status', resolveHotel, enforceTenantAccess, requirePermission(PERMISSIONS.CHAT_RESPOND), chatController.updateConversationStatus);
router.get('/unread', resolveHotel, chatController.getUnreadCounts);
router.delete('/messages/:messageId', chatController.deleteMessage);
export default router;
