import { Router } from 'express';
import * as reviewController from '../controllers/reviewController.js';
import { authenticate, optionalAuthenticate, requirePermission } from '../middlewares/authenticate.js';
import { resolveHotel, enforceTenantAccess } from '../middlewares/tenantScope.js';
import { PERMISSIONS } from '../constants/permissions.js';
const router = Router({ mergeParams: true });
router.use(resolveHotel);
router.get('/', optionalAuthenticate, reviewController.getHotelReviews);
router.get('/:reviewId', reviewController.getReviewById);
router.use(authenticate);
router.get('/check/can-review', reviewController.checkCanReview);
router.post('/', reviewController.createReview);
router.post('/:reviewId/helpful', reviewController.voteHelpful);
router.post('/:reviewId/flag', reviewController.flagReview);
router.get('/admin/all', enforceTenantAccess, requirePermission(PERMISSIONS.REVIEWS_VIEW), reviewController.getAdminReviews);
router.post('/:reviewId/respond', enforceTenantAccess, requirePermission(PERMISSIONS.REVIEWS_VIEW), reviewController.respondToReview);
router.patch('/:reviewId/moderate', enforceTenantAccess, requirePermission(PERMISSIONS.REVIEWS_MODERATE), reviewController.moderateReview);
router.patch('/:reviewId/feature', enforceTenantAccess, requirePermission(PERMISSIONS.REVIEWS_MODERATE), reviewController.toggleFeatured);
export default router;
